### ISSUE TITLE
请教一下这个代码的使用

### ISSUE THREAD

**Issue by lat730** [txtxj/EhuixueShuton#1]
请问要运行这个代码是不是必须要安装好python，还是只要下载谷歌浏览器就可以用

**Comment by txtxj** [comment]
需要安装 Python 3.9 或其他兼容版本，

也需要安装 Chrome 浏览器，并将 chromedriver 放置于系统环境变量中。

如希望使用其他浏览器，也可以将代码中 chromedriver 的部分改为其他浏览器的驱动。

**Comment by lat730** [comment]
好的，谢谢：）
